<?php

/**
 * Implements hook_preprocess_node().
 */
function cp_community_hub_preprocess_node__community_resource(&$variables) {
  $variables['#attached']['library'][] = 'cp_community_hub/style';
}

/**
 * Implements hook_theme().
 */
function cp_community_hub_theme() {
  return [
    'field__node__field_cpcommhub_user_groups' => [
      'template' => 'field--node--field-cpcommhub-tag',
      'base hook' => 'field',
    ],
    'field__node__field_cpcommhub_scope' => [
      'template' => 'field--node--field-cpcommhub-tag',
      'base hook' => 'field',
    ],
    'field__node__field_cpcommhub_link_text' => [
      'template' => 'field--node--field-cpcommhub-link-text',
      'base hook' => 'field',
    ],
    'node__community_resource__full' => [
      'template' => 'node--community-resource--full',
      'base hook' => 'node',
    ],
    'node__community_resource__teaser' => [
      'template' => 'node--community-resource--teaser',
      'base hook' => 'node',
    ],
  ];
}
