<?php

/**
 * Implements hook_preprocess_node().
 */
function cp_community_hub_preprocess_node__community_resource(&$variables) {
  $variables['#attached']['library'][] = 'cp_community_hub/style';
}

/**
 * Implements hook_theme().
 */
function cp_community_hub_theme() {
  return [
    'node__community_resource__teaser' => [
      'template' => 'node--community-resource--teaser',
      'base hook' => 'node',
    ],
  ];
}
