<?php

/**
 * Implements hook_preprocess_views_view().
 */

function cp_spotlights_preprocess_views_view(&$vars) {
  if ($vars['view_array']['#name'] == 'spotlight') {
    $vars['#attached']['library'][] = 'cp_spotlights/style';
  }
}

/**
 * Implements hook_preprocess_block().
 */

function cp_spotlights_preprocess_block(&$vars) {
  if ($vars['derivative_plugin_id'] == 'link_box') {
    $vars['#attached']['library'][] = 'cp_spotlights/style';
  }
}

/**
 * Implements hook_theme().
 */
function cp_spotlights_theme() {
  return [
    'block__inline_block__link_box' => [
      'template' => 'block--bundle--link-box',
      'base hook' => 'block'
    ],
  ];
}
