<?php

/**
 * Implements hook_preprocess_views_view().
 */

function cp_events_preprocess_views_view(&$vars) {
  if ($vars['view']->storage->id() === 'news') {
    $vars['#attached']['library'][] = 'cp_events/style';
  }
}

/**
 * Implements hook_theme().
 */
function cp_events_theme() {
  return [
    'node__cp_event' => [
      'template' => 'node--cp-event',
      'base hook' => 'node'
    ],
    'field__node__field_cp_event_link' => [
      'template' => 'field--node--field-cp-event-link',
      'base hook' => 'field'
    ],
  ];
}