<?php

function cp_forecast_theme_suggestions_node(array $variables) {
  $suggestions = [];

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if ($node->field_template && $node->field_template->value == "forecast") {
      $suggestions[] = 'node__forecast';
    }
  }

  return $suggestions;
}

/**
 * Implements hook_theme().
 */
function cp_forecast_theme() {
  return [
    'node__forecast' => [
      'base hook' => 'node'
    ]
  ];
}