drupal:
  build: .
  links:
   - mariadb
  ports:
   - "8080:80"
  volumes:
   - ../themes:/drupal_files/themes
   - ../modules:/drupal_files/modules
   - ../public_files:/drupal_files/public_files
mariadb:
  image: mariadb:10.0.21
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: xxxxxxxx
    MYSQL_DATABASE: database
    MYSQL_USER: user
    MYSQL_PASSWORD: xxxxxxxx


