drupal:
  build: .
  links:
   - mariadb
  ports:
   - "8080:80"
  volumes:
   - ../themes:/var/www/html/themes
   - ../modules:/var/www/html/modules
   - ../files/default:/var/www/html/sites/default/:rw
mariadb:
  image: mariadb:10.0.21
  ports:
   - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: xxxxxxxx
    MYSQL_DATABASE: database
    MYSQL_USER: user
    MYSQL_PASSWORD: xxxxxxxx
  volumes:
    - ../db:/var/lib/mysql/:rw

