<?php

function cp_station_list_theme_suggestions_node(array $variables) {
  $suggestions = [];

  if ($node = \Drupal::routeMatch()->getParameter('node')) {
    if ($node->field_template && $node->field_template->value == "station-list") {
      $suggestions[] = 'node__station_list';
    }
  }

  return $suggestions;
}

/**
 * Implements hook_theme().
 */
function cp_station_list_theme() {
  return [
    'node__station_list' => [
      'base hook' => 'node'
    ]
  ];
}