<?php

/**
 * Implements hook_preprocess_block().
 */
function cp_data_products_preprocess_block(&$vars) {
  if ($vars['derivative_plugin_id'] == 'data_product_preview') {
    $vars['#attached']['library'][] = 'cp_data_products/script';
    $param = $vars['elements']['content']['field_parameter'][0]['#context']['value'];
    $field_preview_type = $vars['elements']['content']['field_preview_type'];
    $field_keyword = $vars['elements']['content']['field_keyword'];
    $field_show_deprecated = $vars['elements']['content']['field_show_deprecated'];
    $vars['#attached']['drupalSettings']['data_product_preview'][$param] = [
      'spec' => $vars['elements']['content']['field_data_type'][0]['#title'],
      'previewType' => isset($field_preview_type) && !empty($field_preview_type[0]) ? $field_preview_type[0]['#markup'] : '',
      'param' => explode(',', $param),
      'shouldGetHeight' => $vars['elements']['content']['field_display_height'][0]['#markup'] == "On" ? true : false,
      'keyword' => !empty($field_keyword[0]) ? $field_keyword[0]['#context']['value'] : '',
      'showDeprecated' => !empty($field_show_deprecated[0]) && $field_show_deprecated[0]['#markup'] == "On" ? true : false
    ];
  }
}

/**
 * Implements hook_theme().
 */
function cp_data_products_theme() {
  return [
    'block__inline_block__data_product_preview' => [
      'template' => 'block--inline-block--data-product-preview',
      'base hook' => 'block'
    ],
    'field__node__field_link_to_portal_search' => [
      'template' => 'field--node--field-link-to-portal-search',
      'base hook' => 'field'
    ],
    'field__node__field_map_url' => [
      'template' => 'field--node--field-map-url',
      'base hook' => 'field'
    ],
    'views_view_unformatted__data_products__page_1' => [
      'template' => 'views-view-unformatted--data-products--page-1',
      'base hook' => 'view'
    ]
  ];
}